from django.contrib import admin
from . import models

admin.site.register(models.OperatingSystem)
admin.site.register(models.CellNetwork)
admin.site.register(models.PhoneImgUrl)
admin.site.register(models.Bluetooth)
admin.site.register(models.Material)
admin.site.register(models.Platform)
admin.site.register(models.Network)
admin.site.register(models.Storage)
admin.site.register(models.Battery)
admin.site.register(models.Camera)
admin.site.register(models.Sensor)
admin.site.register(models.Phone)
admin.site.register(models.Color)
admin.site.register(models.Sound)
admin.site.register(models.Brand)
admin.site.register(models.Body)
admin.site.register(models.Wifi)
admin.site.register(models.Usb)
admin.site.register(models.Ram)
admin.site.register(models.Gps)
